<?php

return [
    'GS3M' => ['subject' => 'Mathematics', 'age' => 'Standard 3', 'type_of_class' => 'Group', 'fee_per_hour' => 20,],
    'OS3M' => ['subject' => 'Mathematics', 'age' => 'Standard 3', 'type_of_class' => 'One-to-One', 'fee_per_hour' => 25,],
    'GS4M' => ['subject' => 'Mathematics', 'age' => 'Standard 4', 'type_of_class' => 'Group', 'fee_per_hour' => 20,],
    'OS4M' => ['subject' => 'Mathematics', 'age' => 'Standard 4', 'type_of_class' => 'One-to-One', 'fee_per_hour' => 25,],
    'GS5M' => ['subject' => 'Mathematics', 'age' => 'Standard 5', 'type_of_class' => 'Group', 'fee_per_hour' => 20,],
    'OS5M' => ['subject' => 'Mathematics', 'age' => 'Standard 5', 'type_of_class' => 'One-to-One', 'fee_per_hour' => 25,],
    'GS6M' => ['subject' => 'Mathematics', 'age' => 'Standard 6', 'type_of_class' => 'Group', 'fee_per_hour' => 20,],
    'OS6M' => ['subject' => 'Mathematics', 'age' => 'Standard 6', 'type_of_class' => 'One-to-One', 'fee_per_hour' => 25,],
    'GF1M' => ['subject' => 'Mathematics', 'age' => 'Form 1', 'type_of_class' => 'Group', 'fee_per_hour' => 30,],
    'OF1M' => ['subject' => 'Mathematics', 'age' => 'Form 1', 'type_of_class' => 'One-to-One', 'fee_per_hour' => 35,],
    'GF2M' => ['subject' => 'Mathematics', 'age' => 'Form 2', 'type_of_class' => 'Group', 'fee_per_hour' => 30,],
    'OF2M' => ['subject' => 'Mathematics', 'age' => 'Form 2', 'type_of_class' => 'One-to-One', 'fee_per_hour' => 35,],
    'GF3M' => ['subject' => 'Mathematics', 'age' => 'Form 3', 'type_of_class' => 'Group', 'fee_per_hour' => 30,],
    'OF3M' => ['subject' => 'Mathematics', 'age' => 'Form 3', 'type_of_class' => 'One-to-One', 'fee_per_hour' => 35,],
    'GF4M' => ['subject' => 'Mathematics', 'age' => 'Form 4', 'type_of_class' => 'Group', 'fee_per_hour' => 30,],
    'OF4M' => ['subject' => 'Mathematics', 'age' => 'Form 4', 'type_of_class' => 'One-to-One', 'fee_per_hour' => 35,],
    'GF5M' => ['subject' => 'Mathematics', 'age' => 'Form 5', 'type_of_class' => 'Group', 'fee_per_hour' => 30,],
    'OF5M' => ['subject' => 'Mathematics', 'age' => 'Form 5', 'type_of_class' => 'One-to-One', 'fee_per_hour' => 35,],

    'GS3S' => ['subject' => 'Science', 'age' => 'Standard 3', 'type_of_class' => 'Group', 'fee_per_hour' => 20,],
    'OS3S' => ['subject' => 'Science', 'age' => 'Standard 3', 'type_of_class' => 'One-to-One', 'fee_per_hour' => 25,],
    'GS4S' => ['subject' => 'Science', 'age' => 'Standard 4', 'type_of_class' => 'Group', 'fee_per_hour' => 20,],
    'OS4S' => ['subject' => 'Science', 'age' => 'Standard 4', 'type_of_class' => 'One-to-One', 'fee_per_hour' => 25,],
    'GS5S' => ['subject' => 'Science', 'age' => 'Standard 5', 'type_of_class' => 'Group', 'fee_per_hour' => 20,],
    'OS5S' => ['subject' => 'Science', 'age' => 'Standard 5', 'type_of_class' => 'One-to-One', 'fee_per_hour' => 25,],
    'GS6S' => ['subject' => 'Science', 'age' => 'Standard 6', 'type_of_class' => 'Group', 'fee_per_hour' => 20,],
    'OS6S' => ['subject' => 'Science', 'age' => 'Standard 6', 'type_of_class' => 'One-to-One', 'fee_per_hour' => 25,],
    'GF1S' => ['subject' => 'Science', 'age' => 'Form 1', 'type_of_class' => 'Group', 'fee_per_hour' => 30,],
    'OF1S' => ['subject' => 'Science', 'age' => 'Form 1', 'type_of_class' => 'One-to-One', 'fee_per_hour' => 35,],
    'GF2S' => ['subject' => 'Science', 'age' => 'Form 2', 'type_of_class' => 'Group', 'fee_per_hour' => 30,],
    'OF2S' => ['subject' => 'Science', 'age' => 'Form 2', 'type_of_class' => 'One-to-One', 'fee_per_hour' => 35,],
    'GF3S' => ['subject' => 'Science', 'age' => 'Form 3', 'type_of_class' => 'Group', 'fee_per_hour' => 30,],
    'OF3S' => ['subject' => 'Science', 'age' => 'Form 3', 'type_of_class' => 'One-to-One', 'fee_per_hour' => 35,],
    'GF4S' => ['subject' => 'Science', 'age' => 'Form 4', 'type_of_class' => 'Group', 'fee_per_hour' => 30,],
    'OF4S' => ['subject' => 'Science', 'age' => 'Form 4', 'type_of_class' => 'One-to-One', 'fee_per_hour' => 35,],
    'GF5S' => ['subject' => 'Science', 'age' => 'Form 5', 'type_of_class' => 'Group', 'fee_per_hour' => 30,],
    'OF5S' => ['subject' => 'Science', 'age' => 'Form 5', 'type_of_class' => 'One-to-One', 'fee_per_hour' => 35,],

    'GF4A' => ['subject' => 'Add Math', 'age' => 'Form 4', 'type_of_class' => 'Group', 'fee_per_hour' => 40,],
    'OF4A' => ['subject' => 'Add Math', 'age' => 'Form 4', 'type_of_class' => 'One-to-One', 'fee_per_hour' => 50,],
    'GF5A' => ['subject' => 'Add Math', 'age' => 'Form 5', 'type_of_class' => 'Group', 'fee_per_hour' => 40,],
    'OF5A' => ['subject' => 'Add Math', 'age' => 'Form 5', 'type_of_class' => 'One-to-One', 'fee_per_hour' => 50,],

    'GF4C' => ['subject' => 'Chemistry', 'age' => 'Form 4', 'type_of_class' => 'Group', 'fee_per_hour' => 40,],
    'OF4C' => ['subject' => 'Chemistry', 'age' => 'Form 4', 'type_of_class' => 'One-to-One', 'fee_per_hour' => 50,],
    'GF5C' => ['subject' => 'Chemistry', 'age' => 'Form 5', 'type_of_class' => 'Group', 'fee_per_hour' => 40,],
    'OF5C' => ['subject' => 'Chemistry', 'age' => 'Form 5', 'type_of_class' => 'One-to-One', 'fee_per_hour' => 50,],
];
